version: '3'

services:
  urdf-from-step:
    image: urdf-from-step:latest
    volumes:
      - /media/rok/Data4/urdf_dev_ws/src:/input_step_files
      - /home/rok/Documents/urdf_creator:/output_ros_urdf_packages
    #command: stdbuf -o L /bin/bash
    network_mode: "host"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
